### ISSUE TITLE
tracking: distribute the game widely

### ISSUE THREAD

**Issue by brettchalupa** [brettchalupa/sokoworld#25]
keeping track of places it could be nice to explore releasing the game

- [x] itch.io — https://brettchalupa.itch.io/sokoworld
- [ ] dedicated website
- [ ] cargo (kinda fun for rust ppl)
- [ ] mac app store
- [ ] windows store
- [ ] various linux distro app stores
- [ ] homebrew
- [ ] flathub
- [ ] ios
- [ ] android
- [ ] steam
- [ ] xbox pc store thing?
- [ ] epic games store
- [ ] newgrounds
- [ ] other web portal places??
- [ ] windows package managers??
