### ISSUE TITLE
validate levels within a pack

### ISSUE THREAD

**Issue by brettchalupa** [brettchalupa/sokoworld#5]
function that takes a string of level data and ensures it meets specific criteria:

1. enclosed by walls
2. only one player
3. at least one crate
4. a storage location for each crate

this will help ensure the levels I make are valid as well as those added by anyone else

- [x] function w/ unit tests for the various scenarios
- [x] integration test to check each level in the packs
- [x] ~add check for level enclosed by walls~ - extracted to https://github.com/brettchalupa/sokoworld/issues/20
